INSERT INTO products (id, name, description, price, quantity, sku) VALUES
(1, 'Wireless Bluetooth Headphones', 'High-quality wireless headphones with noise cancellation and 20-hour battery life.', 149.99, 50, 'SKU-WBH001'),
(2, '4K Ultra HD Smart TV', '55-inch 4K Ultra HD Smart LED TV with HDR and built-in streaming apps.', 699.99, 30, 'SKU-TV004'),
(3, 'Smartphone with 128GB Storage', 'Latest smartphone with 128GB storage, 12MP camera, and 5G capability.', 999.99, 75, 'SKU-SMRT002'),
(4, 'Gaming Laptop', 'High-performance gaming laptop with NVIDIA graphics and 16GB RAM.', 1299.99, 20, 'SKU-GLP003'),
(5, 'Portable Bluetooth Speaker', 'Compact and waterproof Bluetooth speaker with 12 hours of playtime.', 59.99, 100, 'SKU-BTS005'),
(6, 'Smartwatch with Heart Rate Monitor', 'Fitness smartwatch with heart rate monitoring and GPS tracking.', 199.99, 40, 'SKU-SM001'),
(7, 'Electric Toothbrush', 'Rechargeable electric toothbrush with smart pressure sensor and timer.', 89.99, 80, 'SKU-ETB007'),
(8, 'Air Fryer', 'Healthy air fryer for crispy frying without the oil. 5.8-quart capacity.', 129.99, 25, 'SKU-AF008'),
(9, 'Instant Pot Multi-Cooker', '7-in-1 electric pressure cooker, slow cooker, and rice cooker.', 99.99, 60, 'SKU-IP009'),
(10, 'Robot Vacuum Cleaner', 'Smart robot vacuum cleaner with mapping technology and app control.', 349.99, 15, 'SKU-RVC010'),
(11, 'Digital Camera with 24MP Sensor', 'Compact digital camera with a 24MP sensor and 3-inch LCD.', 499.99, 10, 'SKU-DC011'),
(12, 'Outdoor Camping Tent', 'Spacious 4-person camping tent with waterproof material and easy setup.', 139.99, 45, 'SKU-CT012'),
(13, 'Wireless Charger', 'Fast wireless charging pad compatible with all Qi-enabled devices.', 29.99, 200, 'SKU-WC013'),
(14, 'Gaming Console', 'Next-generation gaming console with 4K gaming and a large library of games.', 499.99, 25, 'SKU-GC014'),
(15, 'Kitchen Knife Set', 'Professional chef knife set with high-carbon stainless steel blades.', 79.99, 55, 'SKU-KNS015'),
(16, 'Electric Kettle', 'BPA-free electric kettle with temperature control and automatic shut-off.', 39.99, 100, 'SKU-EK016'),
(17, 'Yoga Mat', 'Eco-friendly yoga mat with non-slip surface and extra cushioning.', 29.99, 120, 'SKU-YM017'),
(18, 'Wireless Earbuds', 'True wireless earbuds with touch controls and deep bass sound.', 79.99, 90, 'SKU-WE018'),
(19, 'Fitness Tracker', 'Water-resistant fitness tracker with sleep monitoring and step count.', 49.99, 110, 'SKU-FT019'),
(20, 'Backpack with USB Charging Port', 'Stylish backpack with a built-in USB charging port for devices.', 59.99, 70, 'SKU-BP020');
